### PR TITLE
Removed unneeded dependency on LP4J

### PR DESCRIPTION
**Pull request by perkowitz**

### CODE REVIEW

**Comment by lhornby** [comment]
Thanks, will try this soon and report back. Was still left with null pointer exception in the end so couldn't run. Will investigate properly and add another issue if necessary.

**Comment by lhornby** [comment]
Builds fine and solves the dependency issues. Ta!

**Comment by perkowitz** [comment]
The NPE went away too?

**Comment by lhornby** [comment]
Yes. Thankyou!

**Pull request merged**
